### ISSUE TITLE
jhack 4.3.3 is broken with Import Error

### ISSUE THREAD

**Issue by Gu1nness** [canonical/jhack#185]
Any jhack command fails with:
```
Traceback (most recent call last):
  File "/snap/jhack/391/bin/jhack", line 8, in <module>
    sys.exit(main())
  File "/snap/jhack/391/lib/python3.8/site-packages/jhack/main.py", line 46, in main
    from jhack.scenario.snapshot import snapshot
  File "/snap/jhack/391/lib/python3.8/site-packages/jhack/scenario/snapshot.py", line 23, in <module>
    from scenario.runtime import UnitStateDB
  File "/snap/jhack/391/lib/python3.8/site-packages/scenario/__init__.py", line 4, in <module>
    from scenario.context import ActionOutput, Context
  File "/snap/jhack/391/lib/python3.8/site-packages/scenario/context.py", line 13, in <module>
    from scenario.runtime import Runtime
  File "/snap/jhack/391/lib/python3.8/site-packages/scenario/runtime.py", line 19, in <module>
    from scenario.ops_main_mock import NoObserverError
  File "/snap/jhack/391/lib/python3.8/site-packages/scenario/ops_main_mock.py", line 17, in <module>
    from ops.main import CHARM_STATE_FILE, _Dispatcher, _get_charm_dir, _get_event_args
ImportError: cannot import name '_get_charm_dir' from 'ops.main' (/snap/jhack/391/lib/python3.8/site-packages/ops/main.py)
```

Version info:
```
$ sudo snap info jhack
…
installed:          0.4.3.3              (391) 114MB -
```

**Comment by PietroPasotti** [comment]
uh. might accidentally have shipped with too recent an ops. will look into it

**Comment by PietroPasotti** [comment]
actually that's an issue with scenario, which coincidentally I can also fix

**Comment by PietroPasotti** [comment]
will be fixed by: https://github.com/canonical/ops-scenario/pull/182

**Comment by PietroPasotti** [comment]
hotfixed for now by pinning older ops
